<script setup lang="ts">
import { ref, onMounted } from 'vue';

import { useLocationStore } from '../services/location';
import { generateHexPassphrase } from '../services/random';

const locationStore = useLocationStore();

const serverUrl = ref(locationStore.apiBaseUrl);
const deviceTokenInput = ref(locationStore.deviceToken);
const signingKeyInput = ref(locationStore.userSigningKey);
const showSigningKey = ref(false);
const error = ref('');

onMounted(() => {
    if (!signingKeyInput.value.trim()) {
        signingKeyInput.value = generateHexPassphrase();
    }
});

function handleGenerateKey() {
    signingKeyInput.value = generateHexPassphrase();
    error.value = '';
}

function handleCompleteOnboarding() {
    error.value = '';

    try {
        if (serverUrl.value) {
            locationStore.configureServerUrl(serverUrl.value);
        }

        const trimmedToken = deviceTokenInput.value.trim();
        if (!trimmedToken) {
            error.value = 'A valid Sharing ID generated by the server is required.';
            return;
        }

        const trimmedKey = signingKeyInput.value.trim();

        // Validation: Must be 32 bytes (64 hex characters)
        const hexRegex = /^[0-9a-fA-F]{64}$/;
        if (!trimmedKey || !hexRegex.test(trimmedKey)) {
            error.value = 'The Signing Key must be a valid 32-byte hex string (64 characters).';
            return;
        }

        locationStore.setDeviceToken(trimmedToken);
        locationStore.setUserSigningKey(trimmedKey);
        locationStore.isConfigured = true;
    } catch (err: any) {
        error.value = err.message || 'Configuration failed.';
    }
}
</script>

<template>
    <div class="onboarding-overlay">
        <div class="onboarding-card">
            <h2>Welcome to SelfPin</h2>
            <p class="subtitle">Set up your server connection and sharing details to continue.</p>

            <form @submit.prevent="handleCompleteOnboarding">
                <div class="form-group">
                    <label for="serverUrl">Server URL</label>
                    <input id="serverUrl" v-model="serverUrl" type="url"
                        placeholder="https://selfpin.mydomain.example:443" required />
                    <small>Defaults to localhost or configured environment server.</small>
                </div>

                <div class="form-group">
                    <label for="deviceToken">Sharing ID</label>
                    <input id="deviceToken" v-model="deviceTokenInput" type="text" placeholder="Paste your Sharing ID"
                        required />
                    <small>Sharing IDs must be issued directly by the server administrator.</small>
                </div>

                <div class="form-group">
                    <label for="signingKey">Signing Key</label>
                    <div class="input-with-buttons">
                        <input id="signingKey" :type="showSigningKey ? 'text' : 'password'" v-model="signingKeyInput"
                            placeholder="64-character key" />
                        <button type="button" @click="showSigningKey = !showSigningKey" class="btn-secondary">
                            {{ showSigningKey ? 'Hide' : 'Show' }}
                        </button>
                        <button type="button" @click="handleGenerateKey" class="btn-secondary">
                            Generate
                        </button>
                    </div>
                    <small class="warning-text">
                        <strong>Important:</strong> Treat this key like a password. Save it in a secure location to
                        restore your account access on a new device.
                    </small>
                </div>

                <p v-if="error" class="error">{{ error }}</p>

                <button type="submit" class="btn-primary">Connect App</button>
            </form>
        </div>
    </div>
</template>

<style scoped>
.onboarding-overlay,
.onboarding-card,
input,
button,
label,
h2,
p,
small {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    box-sizing: border-box;
}

.onboarding-overlay {
    position: fixed;
    inset: 0;
    background: rgba(15, 23, 42, 0.6);
    backdrop-filter: blur(4px);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 3000;
}

.onboarding-card {
    background: #ffffff;
    width: 90%;
    max-width: 460px;
    padding: 2rem;
    border-radius: 1rem;
    box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1);
}

.onboarding-card h2 {
    margin: 0 0 0.25rem 0;
    font-size: 1.25rem;
    font-weight: 700;
    color: #0f172a;
}

.subtitle {
    color: #64748b;
    font-size: 0.875rem;
    margin-bottom: 1.5rem;
}

.form-group {
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
    margin-bottom: 1.25rem;
    text-align: left;
}

.form-group label {
    font-size: 0.85rem;
    font-weight: 600;
    color: #1e293b;
}

.form-group input {
    padding: 0.65rem;
    border: 1px solid #cbd5e1;
    border-radius: 0.5rem;
    font-size: 16px;
    /* Fixes input auto-zoom on iOS */
}

.input-with-buttons {
    display: flex;
    gap: 0.5rem;
    flex-wrap: wrap;
}

.input-with-buttons input {
    flex: 1 1 140px;
    min-width: 0;
}

.btn-secondary {
    padding: 0.6rem 0.75rem;
    background: #e2e8f0;
    border: none;
    border-radius: 0.5rem;
    font-size: 0.8rem;
    font-weight: 600;
    color: #334155;
    cursor: pointer;
    flex: 0 0 auto;
    white-space: nowrap;
}

.btn-secondary:hover {
    background: #cbd5e1;
}

.form-group small {
    font-size: 0.75rem;
    color: #64748b;
    line-height: 1.3;
}

.warning-text {
    color: #b45309 !important;
    margin-top: 0.25rem;
}

.btn-primary {
    width: 100%;
    padding: 0.75rem;
    background: #2563eb;
    color: #fff;
    border: none;
    border-radius: 0.5rem;
    font-weight: 600;
    font-size: 0.95rem;
    cursor: pointer;
    margin-top: 0.5rem;
}

.btn-primary:hover {
    background: #1d4ed8;
}

.error {
    color: #ef4444;
    font-size: 0.85rem;
    margin-bottom: 1rem;
}
</style>